### ISSUE TITLE
jira password change

### ISSUE THREAD

**Issue by eliasjulian** [atlassian/jira-cloud-for-sketch#10]
I have to change my passwords every few months due to some organization guidelines, so after changing my jira password I'm unable to log out of the plugin to log back in with the new password. I'm getting the "you're not allowed to do that" error message, understandably, but that means I can't access the settings which are only shown after a successful login. 

I'm running the server beta, and I've tried uninstalling the plugin and restarting sketch to no avail. Is there a cached settings or log file I need to delete? Thanks for the help!

**Comment by kannonboy** [comment]
Thanks for the report @eliasjulian! I'll make sure this is fixed in the next beta. In the meantime, you can clear your local Jira for Sketch plugin settings by running the following command from Terminal:

```
/usr/bin/defaults delete ~/Library/Preferences/plugin.sketch.jira-sketch-plugin
```

**Comment by eliasjulian** [comment]
Perfect, all fixed. Thanks @kannonboy!
